# Concat & Append

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.0.3'

In [29]:
# Numeros a mostrar solo con 2 cifras
pd.options.display.float_format = '{:.2f}'.format

In [30]:
# Hacer lo mismo desde numpy
np.set_printoptions(precision=1)

In [31]:
# Matriz de 2 x 5 (valores entre - y 10)
x1 = np.random.rand(2,5)*10
x1

array([[4.9, 6.6, 0.6, 0.5, 8.6],
       [2. , 1.8, 1.6, 7.9, 5.7]])

In [32]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.7, -0.7, -0.4, -0.6, -0.9],
       [-0.1, -0.2, -0.8, -0.5, -0.4]])

In [33]:
# Concatenar 2 matrices
np.concatenate([x1,x2])

array([[ 4.9,  6.6,  0.6,  0.5,  8.6],
       [ 2. ,  1.8,  1.6,  7.9,  5.7],
       [-0.7, -0.7, -0.4, -0.6, -0.9],
       [-0.1, -0.2, -0.8, -0.5, -0.4]])

In [34]:
np.concatenate([x1,x2]).shape

(4, 5)

In [35]:
# Concatenar x columnas
np.concatenate([x1,x2], axis = 1)

array([[ 4.9,  6.6,  0.6,  0.5,  8.6, -0.7, -0.7, -0.4, -0.6, -0.9],
       [ 2. ,  1.8,  1.6,  7.9,  5.7, -0.1, -0.2, -0.8, -0.5, -0.4]])

In [36]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

In [37]:
# Serie de elementos
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   4.92
b   6.56
c   0.64
d   0.47
e   8.65
dtype: float64

In [38]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.72
d   -0.69
e   -0.42
f   -0.55
g   -0.86
dtype: float64

In [39]:
# A lo largo de filas
pd.concat([s1,s2])

a    4.92
b    6.56
c    0.64
d    0.47
e    8.65
c   -0.72
d   -0.69
e   -0.42
f   -0.55
g   -0.86
dtype: float64

In [40]:
# A lo largo de Columnas
pd.concat([s1,s2], axis=1)

0     1
a 4.92   nan
b 6.56   nan
c 0.64 -0.72
d 0.47 -0.69
e 8.65 -0.42
f  nan -0.55
g  nan -0.86

In [41]:
s1.reset_index(drop=True)

0   4.92
1   6.56
2   0.64
3   0.47
4   8.65
dtype: float64

In [42]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 4.92 -0.72
1 6.56 -0.69
2 0.64 -0.42
3 0.47 -0.55
4 8.65 -0.86

In [43]:
# Concatenacion de dataframes
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 4.46 0.73
1 4.01 4.76
2 3.14 5.30

In [44]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.17 -0.05
3 -0.55 -0.19
4 -0.52 -0.79

In [45]:
pd.concat([df1,df2])

a     b
0  4.46  0.73
1  4.01  4.76
2  3.14  5.30
2 -0.17 -0.05
3 -0.55 -0.19
4 -0.52 -0.79

In [46]:
# Concatenar por columnas
pd.concat([df1,df2], axis=1)

a    b     a     b
0 4.46 0.73   nan   nan
1 4.01 4.76   nan   nan
2 3.14 5.30 -0.17 -0.05
3  nan  nan -0.55 -0.19
4  nan  nan -0.52 -0.79

In [47]:
# Solo los indices que se comparten
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 3.14 5.30 -0.17 -0.05

In [48]:
# Concatenar reseteando indices
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 4.46 0.73 -0.17 -0.05
1 4.01 4.76 -0.55 -0.19
2 3.14 5.30 -0.52 -0.79

In [49]:
df1.append(df2).append(df2)

a     b
0  4.46  0.73
1  4.01  4.76
2  3.14  5.30
2 -0.17 -0.05
3 -0.55 -0.19
4 -0.52 -0.79
2 -0.17 -0.05
3 -0.55 -0.19
4 -0.52 -0.79

In [50]:
df1.T

0    1    2
a 4.46 4.01 3.14
b 0.73 4.76 5.30

In [52]:
# Unir a lo largo de las columnas
df1.T.append(df2.T).T

a    b     a     b
0 4.46 0.73   nan   nan
1 4.01 4.76   nan   nan
2 3.14 5.30 -0.17 -0.05
3  nan  nan -0.55 -0.19
4  nan  nan -0.52 -0.79